# Generated by Django 3.2.9 on 2021-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0007_auto_20211120_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='win_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
