# Generated by Django 3.2.9 on 2021-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0008_winner_win_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydraw',
            name='reg_tickets',
            field=models.ManyToManyField(blank=True, to='lucky_draw_api.Ticket'),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='rewards',
            field=models.ManyToManyField(blank=True, to='lucky_draw_api.Reward'),
        ),
    ]
