# Generated by Django 3.2.9 on 2021-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0009_auto_20211120_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckydraw',
            name='timing',
            field=models.TimeField(),
        ),
    ]
