# Generated by Django 3.2.9 on 2021-11-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0011_auto_20211121_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='used_at',
        ),
    ]
