# Generated by Django 3.2.9 on 2021-11-19 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lucky_draw_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckydraw',
            name='winners',
        ),
        migrations.AddField(
            model_name='luckydraw',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='luckydraw',
            name='timing',
            field=models.DateField(),
        ),
    ]
