# Generated by Django 3.2.9 on 2021-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0004_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
