# Generated by Django 3.2.9 on 2021-11-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0005_alter_ticket_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckydraw',
            name='winner',
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lucky_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lucky_draw_api.luckydraw')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lucky_draw_api.reward')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lucky_draw_api.ticket')),
            ],
        ),
    ]
