# Generated by Django 3.2.9 on 2021-11-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucky_draw_api', '0006_auto_20211120_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luckydraw',
            old_name='participants',
            new_name='reg_tickets',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='announce_date',
            new_name='redeem_date',
        ),
    ]
